dev: order-dev.yml
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/pm111?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.102
    username: guest
    password: guest
    port: 5672
  application:
    name: order
server:
  port: 8082
