dev: product-dev
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///pm111?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.102
    username: guest
    password: guest
    port: 5672
server:
  port: 8081
